const vendingData = [
  {"retailer": "Safeway", "machineId": "Q01036", "address": "2227 S Shore Center, Alameda, CA"},
  {"retailer": "Safeway", "machineId": "Q01268", "address": "2600 5th St, Alameda, CA"},
  {"retailer": "Safeway", "machineId": "Q01528", "address": "103 American Canyon Rd, American Canyon, CA"},
  {"retailer": "Food 4 Less", "machineId": "Q00330", "address": "1616 W Katella Ave, Anaheim, CA"},
  {"retailer": "Albertsons", "machineId": "Q00491", "address": "810 S State College Blvd, Anaheim, CA"},
  {"retailer": "Vons", "machineId": "Q00695", "address": "5600 E Santa Ana Canyon Rd, Anaheim, CA"},
  {"retailer": "Safeway", "machineId": "Q01333", "address": "16 Rancho del Mar, Aptos, CA"},
  {"retailer": "Albertsons", "machineId": "Q00467", "address": "298 Live Oak Ave, Arcadia, CA"},
  {"retailer": "Vons", "machineId": "Q00715", "address": "745 W Naomi Ave, Arcadia, CA"},
  {"retailer": "Safeway", "machineId": "Q00918", "address": "2550 Bell Rd, Auburn, CA"},
  {"retailer": "Food 4 Less", "machineId": "Q00573", "address": "3000 Baldwin Park Blvd, Baldwin Park, CA"},
  {"retailer": "Food 4 Less", "machineId": "Q00711", "address": "6901 Eastern Ave, Bell Gardens, CA"},
  {"retailer": "Safeway", "machineId": "Q01083", "address": "1100 El Camino Real, Belmont, CA"},
  {"retailer": "Safeway", "machineId": "Q01274", "address": "50 Solano Square, Benicia, CA"},
  {"retailer": "Safeway", "machineId": "Q01020", "address": "1444 Shattuck Pl, Berkeley, CA"},
  {"retailer": "WinCo Foods", "machineId": "Q00597", "address": "6700 Lone Tree Wy, Brentwood, CA"},
  {"retailer": "Vons", "machineId": "Q00314", "address": "301 N Pass Ave, Burbank, CA"},
  {"retailer": "Albertsons", "machineId": "Q00523", "address": "26521 Agoura Rd, Calabasas, CA"},
  {"retailer": "Vons", "machineId": "Q01242", "address": "940 Arneill Rd, Camarillo, CA"},
  {"retailer": "Safeway", "machineId": "Q00974", "address": "3380 Coach Ln, Cameron Park, CA"},
  {"retailer": "Safeway", "machineId": "Q00971", "address": "2341 S Winchester Blvd, Campbell, CA"},
  {"retailer": "Safeway", "machineId": "Q01539", "address": "950 W Hamilton Ave, Campbell, CA"},
  {"retailer": "Vons", "machineId": "Q00875", "address": "2560 El Camino Real, Carlsbad, CA"},
  {"retailer": "Vons", "machineId": "Q01024", "address": "6951 El Camino Real, Carlsbad, CA"},
  {"retailer": "Safeway", "machineId": "Q00989", "address": "4040 Manzanita Ave, Carmichael, CA"},
  {"retailer": "Albertsons", "machineId": "Q00722", "address": "200 E Sepulveda Blvd, Carson, CA"},
  {"retailer": "Safeway", "machineId": "Q01102", "address": "4015 E Castro Valley Blvd, Castro Valley, CA"},
  {"retailer": "Albertsons", "machineId": "Q00509", "address": "12013 Central Ave, Chino, CA"},
  {"retailer": "Albertsons", "machineId": "Q00519", "address": "15970 Los Serranos Country Club Dr, Chino Hills, CA"},
  {"retailer": "Albertsons", "machineId": "Q01243", "address": "3255 Grand Ave, Chino Hills, CA"},
  {"retailer": "Vons", "machineId": "Q00331", "address": "1745 Eastlake Pkwy, Chula Vista, CA"},
  {"retailer": "Vons", "machineId": "Q01032", "address": "2250 Otay Lakes Rd, Chula Vista, CA"},
  {"retailer": "Albertsons", "machineId": "Q01670", "address": "720 3rd Ave, Chula Vista, CA"},
  {"retailer": "Ralphs", "machineId": "Q01791", "address": "659 E Palomar St, Chula Vista, CA"},
  {"retailer": "Safeway", "machineId": "Q00941", "address": "7301 Greenback Ln, Citrus Heights, CA"},
  {"retailer": "Food 4 Less", "machineId": "Q00409", "address": "1900 W Rosecrans Ave, Compton, CA"},
  {"retailer": "Safeway", "machineId": "Q00970", "address": "2600 Willow Pass Rd, Concord, CA"},
  {"retailer": "Safeway", "machineId": "Q01279", "address": "4309 Clayton Rd, Concord, CA"},
  {"retailer": "Albertsons", "machineId": "Q00388", "address": "260 W Foothill Pkwy, Corona, CA"},
  {"retailer": "Vons", "machineId": "Q00508", "address": "535 N McKinley St, Corona, CA"},
  {"retailer": "Vons", "machineId": "Q00511", "address": "11800 De Palma Rd, Corona, CA"},
  {"retailer": "Safeway", "machineId": "Q01512", "address": "137 Corte Madera Town Center, Corte Madera, CA"},
  {"retailer": "Pavilions", "machineId": "Q00517", "address": "11030 Jefferson Blvd, Culver City, CA"},
  {"retailer": "Safeway", "machineId": "Q01486", "address": "20620 W Homestead Rd, Cupertino, CA"},
  {"retailer": "Safeway", "machineId": "Q01516", "address": "601 Westlake Center, Daly City, CA"},
  {"retailer": "Safeway", "machineId": "Q01151", "address": "3496 Camino Tassajara, Danville, CA"},
  {"retailer": "Safeway", "machineId": "Q01320", "address": "1235 Stratford Ave, Dixon, CA"},
  {"retailer": "Food 4 Less", "machineId": "Q00311", "address": "13525 Lakewood Blvd, Downey, CA"},
  {"retailer": "Ralphs", "machineId": "Q00739", "address": "8626 Firestone Blvd, Downey, CA"},
  {"retailer": "Safeway", "machineId": "Q00928", "address": "7499 Dublin Blvd, Dublin, CA"},
  {"retailer": "Safeway", "machineId": "Q00930", "address": "4440 Tassajara Rd, Dublin, CA"},
  {"retailer": "Albertsons", "machineId": "Q00655", "address": "7070 Archibald Ave, Eastvale, CA"},
  {"retailer": "Vons", "machineId": "Q01167", "address": "6170 Hamner Ave, Eastvale, CA"},
  {"retailer": "Albertsons", "machineId": "Q00474", "address": "1608 Broadway, El Cajon, CA"},
  {"retailer": "Vons", "machineId": "Q00886", "address": "1201 Avocado Ave, El Cajon, CA"},
  {"retailer": "Albertsons", "machineId": "Q01247", "address": "2899 Jamacha Rd, El Cajon, CA"},
  {"retailer": "Safeway", "machineId": "Q01018", "address": "11450 San Pablo Ave, El Cerrito, CA"},
  {"retailer": "Safeway", "machineId": "Q00938", "address": "2207 Francisco Dr, El Dorado Hills, CA"},
  {"retailer": "Safeway", "machineId": "Q00977", "address": "3383 Bass Lake Rd, El Dorado Hills, CA"},
  {"retailer": "Safeway", "machineId": "Q00931", "address": "5021 Laguna Blvd, Elk Grove, CA"},
  {"retailer": "WinCo Foods", "machineId": "Q01530", "address": "8124 Sheldon Rd, Elk Grove, CA"},
  {"retailer": "Pak N Save", "machineId": "Q01060", "address": "3889 San Pablo Ave, Emeryville, CA"},
  {"retailer": "Albertsons", "machineId": "Q00890", "address": "1570 W Valley Pkwy, Escondido, CA"},
  {"retailer": "Vons", "machineId": "Q00892", "address": "1000 W El Norte Pkwy, Escondido, CA"},
  {"retailer": "Vons", "machineId": "Q01030", "address": "351 W Felicita Ave, Escondido, CA"},
  {"retailer": "Food 4 Less", "machineId": "Q01250", "address": "644 N Broadway, Escondido, CA"},
  {"retailer": "Safeway", "machineId": "Q00943", "address": "5450 Dewey Dr, Fair\u00a0Oaks, CA"},
  {"retailer": "Safeway", "machineId": "Q01334", "address": "2401 Waterman Blvd, Fairfield, CA"},
  {"retailer": "Albertsons", "machineId": "Q00476", "address": "1133 S Mission Rd, Fallbrook, CA"},
  {"retailer": "Vons", "machineId": "Q00481", "address": "636 Ventura St, Fillmore, CA"},
  {"retailer": "WinCo Foods", "machineId": "Q00690", "address": "200 Blue Ravine Rd, Folsom, CA"},
  {"retailer": "Safeway", "machineId": "Q00981", "address": "1850 Prairie City Rd, Folsom, CA"},
  {"retailer": "WinCo Foods", "machineId": "Q00493", "address": "14338 Foothill Blvd, Fontana, CA"},
  {"retailer": "Vons", "machineId": "Q00563", "address": "7390 Cherry Ave, Fontana, CA"},
  {"retailer": "Safeway", "machineId": "Q01239", "address": "921 E Hillsdale Blvd, Foster City, CA"},
  {"retailer": "Albertsons", "machineId": "Q00328", "address": "16061 Brookhurst St, Fountain Valley, CA"},
  {"retailer": "Safeway", "machineId": "Q01337", "address": "2010 Freedom Blvd, Freedom, CA"},
  {"retailer": "Safeway", "machineId": "Q00973", "address": "39100 Argonaut Way, Fremont, CA"},
  {"retailer": "Safeway", "machineId": "Q01026", "address": "3902 Washington Blvd, Fremont, CA"},
  {"retailer": "Safeway", "machineId": "Q01529", "address": "6150 Bollinger Rd, San Jose, CA"},
  {"retailer": "Safeway", "machineId": "Q01160", "address": "699 Lewelling Blvd, San Leandro, CA"},
  {"retailer": "WinCo Foods", "machineId": "Q00479", "address": "555 Grand Ave, San Marcos, CA"},
  {"retailer": "Albertsons", "machineId": "Q00502", "address": "151 Woodland Pkwy, San Marcos, CA"},
  {"retailer": "Albertsons", "machineId": "Q00877", "address": "1929 W San Marcos Blvd, San Marcos, CA"},
  {"retailer": "Albertsons", "machineId": "Q01022", "address": "1571 San Elijo Rd, San Marcos, CA"},
  {"retailer": "Safeway", "machineId": "Q01134", "address": "100 De Anza Blvd, San Mateo, CA"},
  {"retailer": "Safeway", "machineId": "Q01260", "address": "1655 S El Camino Real, San Mateo, CA"},
  {"retailer": "Safeway", "machineId": "Q01039", "address": "11060 Bollinger Canyon Rd, San Ramon, CA"},
  {"retailer": "Food 4 Less", "machineId": "Q00320", "address": "2140 S Bristol St, Santa Ana, CA"},
  {"retailer": "Vons", "machineId": "Q00414", "address": "3650 S Bristol St, Santa Ana, CA"},
  {"retailer": "Albertsons", "machineId": "Q00478", "address": "23850 Copper Hill Dr, Santa Clarita, CA"},
  {"retailer": "Albertsons", "machineId": "Q00487", "address": "27631 Bouquet Canyon Rd, Santa Clarita, CA"},
  {"retailer": "Vons", "machineId": "Q01184", "address": "24160 Lyons Ave, Santa Clarita, CA"},
  {"retailer": "Vons", "machineId": "Q01223", "address": "26518 Bouquet Canyon Rd, Santa Clarita, CA"},
  {"retailer": "Food 4 Less", "machineId": "Q01656", "address": "19200 Soledad Canyon Rd, Santa Clarita, CA"},
  {"retailer": "Safeway", "machineId": "Q01338", "address": "2203 Mission St, Santa Cruz, CA"},
  {"retailer": "Vons", "machineId": "Q00513", "address": "576 W Main St, Santa Paula, CA"},
  {"retailer": "Safeway", "machineId": "Q01514", "address": "406 N Main St, Sebastopol, CA"},
  {"retailer": "Albertsons", "machineId": "Q00465", "address": "1268 Madera Rd, Simi Valley, CA"},
  {"retailer": "Vons", "machineId": "Q00486", "address": "1855 Cochran St, Simi Valley, CA"},
  {"retailer": "Vons", "machineId": "Q00504", "address": "2938 Tapo Canyon Rd, Simi Valley, CA"},
  {"retailer": "Safeway", "machineId": "Q01536", "address": "477 W Napa St, Sonoma, CA"},
  {"retailer": "Safeway", "machineId": "Q01351", "address": "30 Chestnut Ave, South San Francisco, CA"},
  {"retailer": "Safeway", "machineId": "Q01532", "address": "2255 Gellert Blvd, South San Francisco, CA"},
  {"retailer": "Albertsons", "machineId": "Q01218", "address": "543 Sweetwater Rd, Spring Valley, CA"},
  {"retailer": "Vons", "machineId": "Q01216", "address": "25850 The Old Rd, Stevenson Ranch, CA"},
  {"retailer": "Ralphs", "machineId": "Q01690", "address": "24975 Pico Canyon Rd, Stevenson Ranch, CA"},
  {"retailer": "Safeway", "machineId": "Q00975", "address": "6445 Pacific Ave, Stockton, CA"},
  {"retailer": "Safeway", "machineId": "Q01057", "address": "2808 Country Club Blvd, Stockton, CA"},
  {"retailer": "Safeway", "machineId": "Q00611", "address": "639 S Bernardo Ave, Sunnyvale, CA"},
  {"retailer": "Safeway", "machineId": "Q01503", "address": "150 E El Camino Real, Sunnyvale, CA"},
  {"retailer": "WinCo Foods", "machineId": "Q01185", "address": "40435 Winchester Rd, Temecula, CA"},
  {"retailer": "Vons", "machineId": "Q00507", "address": "2048 E Avenida de Los Arboles, Thousand Oaks, CA"},
  {"retailer": "Vons", "machineId": "Q00423", "address": "4705 Torrance Blvd, Torrance, CA"},
  {"retailer": "Vons", "machineId": "Q00706", "address": "24325 Crenshaw Blvd, Torrance, CA"},
  {"retailer": "Safeway", "machineId": "Q00972", "address": "1801 W 11th St, Tracy, CA"},
  {"retailer": "Safeway", "machineId": "Q00936", "address": "2800 Ygnacio Valley Rd, Walnut Creek, CA"},
  {"retailer": "Food 4 Less", "machineId": "Q00248", "address": "615 N Azusa Ave, West Covina, CA"},
  {"retailer": "Pavilions", "machineId": "Q00415", "address": "8969 Santa Monica Blvd, West Hollywood, CA"},
  {"retailer": "Vons", "machineId": "Q00501", "address": "Westchester area, Los Angeles, CA"},
  {"retailer": "Albertsons", "machineId": "Q00662", "address": "6755 Westminster Blvd, Westminster, CA"},
  {"retailer": "Vons", "machineId": "Q00327", "address": "15740 La Forge St, Whittier, CA"},
  {"retailer": "Safeway", "machineId": "Q01524", "address": "9080 Brooks Rd, Windsor, CA"},
  {"retailer": "Vons", "machineId": "Q01240", "address": "20445 Yorba Linda Blvd, Yorba Linda, CA"},
  {"retailer": "Vons", "machineId": "Q00503", "address": "33644 Yucaipa Blvd, Yucaipa, CA"},
  {"retailer": "Albertsons", "machineId": "Q00332", "address": "1930 N Placentia Ave, Fullerton, CA"},
  {"retailer": "Vons", "machineId": "Q00717", "address": "11861 Valley View St, Garden Grove, CA"},
  {"retailer": "Vons", "machineId": "Q00658", "address": "1260 W Redondo Beach Blvd, Gardena, CA"},
  {"retailer": "Albertsons", "machineId": "Q00732", "address": "1735 Artesia Blvd, Gardena, CA"},
  {"retailer": "Food 4 Less", "machineId": "Q01249", "address": "1299 Artesia Blvd, Gardena, CA"},
  {"retailer": "Vons", "machineId": "Q00417", "address": "561 N Glendale Ave, Glendale, CA"},
  {"retailer": "Vons", "machineId": "Q00699", "address": "311 W Los Feliz Rd, Glendale, CA"},
  {"retailer": "Albertsons", "machineId": "Q00427", "address": "133 W Rte 66, Glendora, CA"},
  {"retailer": "Vons", "machineId": "Q01245", "address": "163 S Turnpike Rd, Goleta, CA"},
  {"retailer": "Vons", "machineId": "Q00707", "address": "2122 S Hacienda Blvd, Hacienda Heights, CA"},
  {"retailer": "Safeway", "machineId": "Q01277", "address": "70 Cabrillo Hwy, Half Moon Bay, CA"},
  {"retailer": "Food 4 Less", "machineId": "Q00315", "address": "14500 Ocean Gate Ave, Hawthorne, CA"},
  {"retailer": "FoodMaxx", "machineId": "Q00626", "address": "27300 Hesperian Blvd, Hayward, CA"},
  {"retailer": "Safeway", "machineId": "Q01051", "address": "22280 Foothill Blvd, Hayward, CA"},
  {"retailer": "Safeway", "machineId": "Q01278", "address": "231 W Jackson St, Hayward, CA"},
  {"retailer": "Safeway", "machineId": "Q01502", "address": "1115 Vine St, Healdsburg, CA"},
  {"retailer": "WinCo Foods", "machineId": "Q00453", "address": "4602 W Florida Ave, Hemet, CA"},
  {"retailer": "Safeway", "machineId": "Q00939", "address": "4080 San Pablo Ave, Hercules, CA"},
  {"retailer": "Vons", "machineId": "Q00721", "address": "715 Pier Ave, Hermosa Beach, CA"},
  {"retailer": "Vons", "machineId": "Q00322", "address": "5922 Edinger Ave, Huntington Beach, CA"},
  {"retailer": "Albertsons", "machineId": "Q00325", "address": "7201 Yorktown Ave, Huntington Beach, CA"},
  {"retailer": "Albertsons", "machineId": "Q00483", "address": "19640 Beach Blvd, Huntington Beach, CA"},
  {"retailer": "Food 4 Less", "machineId": "Q00418", "address": "6920 Santa Fe Ave, Huntington Park, CA"},
  {"retailer": "Food 4 Less", "machineId": "Q00380", "address": "3200 W Century Blvd, Inglewood, CA"},
  {"retailer": "Vons", "machineId": "Q00422", "address": "500 E Manchester Blvd, Inglewood, CA"},
  {"retailer": "Albertsons", "machineId": "Q00416", "address": "14201 Jeffrey Rd, Irvine, CA"},
  {"retailer": "Albertsons", "machineId": "Q00590", "address": "4541 Campus Dr, Irvine, CA"},
  {"retailer": "Albertsons", "machineId": "Q01285", "address": "6601 Quail Hill Pkwy, Irvine, CA"},
  {"retailer": "Safeway", "machineId": "Q00922", "address": "12110 Industry Blvd, Jackson, CA"},
  {"retailer": "Vons", "machineId": "Q01241", "address": "3233 Foothill Blvd, La Crescenta-Montrose, CA"},
  {"retailer": "Albertsons", "machineId": "Q00583", "address": "1800 W Whittier Blvd, La Habra, CA"},
  {"retailer": "Albertsons", "machineId": "Q00878", "address": "8920 Fletcher Pkwy, La Mesa, CA"},
  {"retailer": "Albertsons", "machineId": "Q01777", "address": "15200 Rosecrans Ave, La Mirada, CA"},
  {"retailer": "Food 4 Less", "machineId": "Q00338", "address": "1821 N Hacienda Blvd, La Puente, CA"},
  {"retailer": "Vons", "machineId": "Q00515", "address": "1600 Foothill Blvd, La Verne, CA"},
  {"retailer": "Albertsons", "machineId": "Q00498", "address": "27702 Crown Valley Pkwy B, Ladera Ranch, CA"},
  {"retailer": "Albertsons", "machineId": "Q01007", "address": "30241 Golden Lantern, Laguna Niguel, CA"},
  {"retailer": "Albertsons", "machineId": "Q00518", "address": "30901 Riverside Dr, Lake Elsinore, CA"},
  {"retailer": "Vons", "machineId": "Q00317", "address": "4226 Woodruff Ave, Lakewood, CA"},
  {"retailer": "Vons", "machineId": "Q00740", "address": "5500 Woodruff Ave, Lakewood, CA"},
  {"retailer": "WinCo Foods", "machineId": "Q01286", "address": "3400 E South St, Lakewood, CA"},
  {"retailer": "Safeway", "machineId": "Q00987", "address": "1554 First St, Livermore, CA"},
  {"retailer": "Safeway", "machineId": "Q01049", "address": "4495 First St, Livermore, CA"},
  {"retailer": "Vons", "machineId": "Q00654", "address": "1800-2000 Ximeno Ave, Long Beach, CA"},
  {"retailer": "Food 4 Less", "machineId": "Q00720", "address": "3210 E Anaheim St, Long Beach, CA"},
  {"retailer": "Albertsons", "machineId": "Q01019", "address": "101 E Willow St, Long Beach, CA"},
  {"retailer": "Safeway", "machineId": "Q01517", "address": "160 1st St, Los Altos, CA"},
  {"retailer": "Albertsons", "machineId": "Q00177", "address": "28090 S Western Ave, Los Angeles, CA"},
  {"retailer": "Food 4 Less", "machineId": "Q00319", "address": "9635 Laurel Canyon Blvd, Los Angeles, CA"},
  {"retailer": "Food 4 Less", "machineId": "Q00324", "address": "5100 N Figueroa St, Los Angeles, CA"},
  {"retailer": "Vons", "machineId": "Q00336", "address": "3461 W 3rd St, Los Angeles, CA"},
  {"retailer": "Food 4 Less", "machineId": "Q00370", "address": "16530 Sherman Way, Los Angeles, CA"},
  {"retailer": "Food 4 Less", "machineId": "Q00386", "address": "11507 S Western Ave, Los Angeles, CA"},
  {"retailer": "Food 4 Less", "machineId": "Q00391", "address": "11840 Wilmington Ave, Los Angeles, CA"},
  {"retailer": "Food 4 Less", "machineId": "Q00410", "address": "336 W Anaheim St, Los Angeles, CA"},
  {"retailer": "Food 4 Less", "machineId": "Q00411", "address": "18318 Vanowen St, Los Angeles, CA"},
  {"retailer": "Food 4 Less", "machineId": "Q00412", "address": "8035 Webb Ave, Los Angeles, CA"},
  {"retailer": "Food 4 Less", "machineId": "Q00413", "address": "1820 W Slauson Ave, Los Angeles, CA"},
  {"retailer": "Food 4 Less", "machineId": "Q00419", "address": "16208 Parthenia St, Los Angeles, CA"},
  {"retailer": "Food 4 Less", "machineId": "Q00420", "address": "2750 1st St, Los Angeles, CA"},
  {"retailer": "Vons", "machineId": "Q00425", "address": "4520 W Sunset Blvd, Los Angeles, CA"},
  {"retailer": "Pavilions", "machineId": "Q00469", "address": "14845 Ventura Blvd, Los Angeles, CA"},
  {"retailer": "Pavilions", "machineId": "Q00514", "address": "6534 Platt Ave, Los Angeles, CA"},
  {"retailer": "Vons", "machineId": "Q00577", "address": "7789 Foothill Blvd, Los Angeles, CA"},
  {"retailer": "Vons", "machineId": "Q00702", "address": "16830 San Fernando Mission Blvd, Los Angeles, CA"},
  {"retailer": "Vons", "machineId": "Q00719", "address": "7311 N Figueroa St, Los Angeles, CA"},
  {"retailer": "Food 4 Less", "machineId": "Q01694", "address": "12689 Glenoaks Blvd, Los Angeles, CA"},
  {"retailer": "Safeway", "machineId": "Q00978", "address": "470 N Santa Cruz Ave, Los Gatos, CA"},
  {"retailer": "Safeway", "machineId": "Q00983", "address": "15549 Union Ave, Los Gatos, CA"},
  {"retailer": "Safeway", "machineId": "Q00980", "address": "1187 S Main St, Manteca, CA"},
  {"retailer": "Pavilions", "machineId": "Q00512", "address": "4365 Glencoe Ave, Marina del Rey, CA"},
  {"retailer": "Safeway", "machineId": "Q01109", "address": "6688 Alhambra Ave, Martinez, CA"},
  {"retailer": "Safeway", "machineId": "Q01330", "address": "525 El Camino Real, Menlo Park, CA"},
  {"retailer": "Safeway", "machineId": "Q01510", "address": "525 El Camino Real, Millbrae, CA"},
  {"retailer": "Safeway", "machineId": "Q00982", "address": "555 E Calaveras Blvd, Milpitas, CA"},
  {"retailer": "Albertsons", "machineId": "Q00575", "address": "23072 Alicia Pkwy, Mission Viejo, CA"},
  {"retailer": "Pavilions", "machineId": "Q01270", "address": "26022 Marguerite Pkwy, Mission Viejo, CA"},
  {"retailer": "Vons", "machineId": "Q00335", "address": "130 W Foothill Blvd, Monrovia, CA"},
  {"retailer": "Albertsons", "machineId": "Q00704", "address": "2469 Via Campo, Montebello, CA"},
  {"retailer": "Safeway", "machineId": "Q01233", "address": "1355 Moraga Way, Moraga, CA"},
  {"retailer": "WinCo Foods", "machineId": "Q00497", "address": "12880 Day St, Moreno Valley, CA"},
  {"retailer": "Food 4 Less", "machineId": "Q01796", "address": "24440 Alessandro Blvd, Moreno Valley, CA"},
  {"retailer": "Safeway", "machineId": "Q00932", "address": "235 Tennant Station, Morgan Hill, CA"},
  {"retailer": "Safeway", "machineId": "Q00985", "address": "840 E Dunne Ave, Morgan Hill, CA"},
  {"retailer": "Safeway", "machineId": "Q01271", "address": "645 San Antonio Rd, Mountain View, CA"},
  {"retailer": "Safeway", "machineId": "Q01513", "address": "1750 Miramonte Ave, Mountain View, CA"},
  {"retailer": "Safeway", "machineId": "Q01538", "address": "570 N Shoreline Blvd, Mountain View, CA"},
  {"retailer": "Albertsons", "machineId": "Q00485", "address": "39140 Winchester Rd, Murrieta, CA"},
  {"retailer": "Albertsons", "machineId": "Q00495", "address": "41000 California Oaks Rd, Murrieta, CA"},
  {"retailer": "Pavilions", "machineId": "Q00995", "address": "21181 Newport Coast Dr, Newport Beach, CA"},
  {"retailer": "Safeway", "machineId": "Q01519", "address": "5720 Nave Dr, Novato, CA"},
  {"retailer": "FoodMaxx", "machineId": "Q00984", "address": "3000 E 9th St, Oakland, CA"},
  {"retailer": "Safeway", "machineId": "Q01126", "address": "5100 Broadway, Oakland, CA"},
  {"retailer": "Safeway", "machineId": "Q01164", "address": "4100 Redwood Rd, Oakland, CA"},
  {"retailer": "Safeway", "machineId": "Q01267", "address": "6310 College Ave, Oakland, CA"},
  {"retailer": "Albertsons", "machineId": "Q00668", "address": "3450 Marron Rd, Oceanside, CA"},
  {"retailer": "Albertsons", "machineId": "Q00751", "address": "4150 Oceanside Blvd, Oceanside, CA"},
  {"retailer": "Vons", "machineId": "Q01005", "address": "845 College Blvd, Oceanside, CA"},
  {"retailer": "WinCo Foods", "machineId": "Q01300", "address": "2245 S El Camino Real, Oceanside, CA"},
  {"retailer": "Food 4 Less", "machineId": "Q01176", "address": "2246 S Euclid Ave, Ontario, CA"},
  {"retailer": "Vons", "machineId": "Q00591", "address": "2684 N Tustin St, Orange, CA"},
  {"retailer": "WinCo Foods", "machineId": "Q01251", "address": "8701 Greenback Ln, Orangevale, CA"},
  {"retailer": "Vons", "machineId": "Q00494", "address": "2101 N Rose Ave, Oxnard, CA"},
  {"retailer": "Safeway", "machineId": "Q01344", "address": "1380 Linda Mar Shopping Center, Pacifica, CA"},
  {"retailer": "Safeway", "machineId": "Q01387", "address": "709 Hickey Blvd, Pacifica, CA"},
  {"retailer": "Vons", "machineId": "Q00372", "address": "2355 E Colorado Blvd, Pasadena, CA"},
  {"retailer": "Safeway", "machineId": "Q01492", "address": "701 Sonoma Mountain Pkwy, Petaluma, CA"},
  {"retailer": "Safeway", "machineId": "Q01525", "address": "389 S McDowell Blvd, Petaluma, CA"},
  {"retailer": "Safeway", "machineId": "Q00969", "address": "3955 Missouri Flat Rd, Placerville, CA"},
  {"retailer": "Safeway", "machineId": "Q00967", "address": "600 Patterson Blvd, Pleasant Hill, CA"},
  {"retailer": "Safeway", "machineId": "Q01031", "address": "1978 Contra Costa Blvd, Pleasant Hill, CA"},
  {"retailer": "Safeway", "machineId": "Q01148", "address": "707 Contra Costa Blvd, Pleasant Hill, CA"},
  {"retailer": "Safeway", "machineId": "Q00944", "address": "1701 Santa Rita Rd, Pleasanton, CA"},
  {"retailer": "WinCo Foods", "machineId": "Q01236", "address": "90 Rio Rancho Rd, Pomona, CA"},
  {"retailer": "Safeway", "machineId": "Q00935", "address": "10635 Folsom Blvd, Rancho Cordova, CA"},
  {"retailer": "Albertsons", "machineId": "Q00468", "address": "11358 Kenyon Way, Rancho Cucamonga, CA"},
  {"retailer": "Albertsons", "machineId": "Q00475", "address": "450 E Cypress Ave, Redlands, CA"},
  {"retailer": "Vons", "machineId": "Q00741", "address": "4001 Inglewood Ave, Redondo Beach, CA"},
  {"retailer": "Albertsons", "machineId": "Q00500", "address": "2975 Van Buren Boulevard, Riverside, CA"},
  {"retailer": "Vons", "machineId": "Q01097", "address": "3520 Riverside Plaza Dr, Riverside, CA"},
  {"retailer": "Food 4 Less", "machineId": "Q01129", "address": "4250 Van Buren Boulevard, Riverside, CA"},
  {"retailer": "Safeway", "machineId": "Q00631", "address": "2220 Sunset Blvd, Rocklin, CA"},
  {"retailer": "Safeway", "machineId": "Q00603", "address": "6340 Commerce Blvd, Rohnert Park, CA"},
  {"retailer": "Pavilions", "machineId": "Q00714", "address": "7 Peninsula Center, Rolling Hills Estates, CA"},
  {"retailer": "Safeway", "machineId": "Q00923", "address": "8640 Sierra College Blvd, Roseville, CA"},
  {"retailer": "Safeway", "machineId": "Q00927", "address": "1080 Pleasant Grove Blvd, Roseville, CA"},
  {"retailer": "Safeway", "machineId": "Q00929", "address": "989 Sunrise Ave, Roseville, CA"},
  {"retailer": "Safeway", "machineId": "Q00988", "address": "9045 Woodcreek Oaks Blvd, Roseville, CA"},
  {"retailer": "Safeway", "machineId": "Q00924", "address": "1814 19th St, Sacramento, CA"},
  {"retailer": "Safeway", "machineId": "Q00926", "address": "1025 Alhambra Blvd, Sacramento, CA"},
  {"retailer": "Safeway", "machineId": "Q00933", "address": "3320 Arden Wy, Sacramento, CA"},
  {"retailer": "Safeway", "machineId": "Q00968", "address": "8377 Elk Grove Florin Rd, Sacramento, CA"},
  {"retailer": "Safeway", "machineId": "Q01522", "address": "5345 Elkhorn Blvd, Sacramento, CA"},
  {"retailer": "WinCo Foods", "machineId": "Q01534", "address": "2300 Watt Ave, Sacramento, CA"},
  {"retailer": "Safeway", "machineId": "Q01537", "address": "2851 Del Paso Rd, Sacramento, CA"},
  {"retailer": "Safeway", "machineId": "Q01500", "address": "838 Sir Francis Drake Blvd, San Anselmo, CA"},
  {"retailer": "Albertsons", "machineId": "Q00521", "address": "804 Avenida Pico, San Clemente, CA"},
  {"retailer": "Pavilions", "machineId": "Q01291", "address": "989 Avenida Pico, San Clemente, CA"},
  {"retailer": "Vons", "machineId": "Q00489", "address": "620 Dennery Rd, San Diego, CA"},
  {"retailer": "Vons", "machineId": "Q00492", "address": "11986 Bernardo Plaza Dr, San Diego, CA"},
  {"retailer": "Vons", "machineId": "Q00499", "address": "6155 El Cajon Blvd, San Diego, CA"},
  {"retailer": "Vons", "machineId": "Q00505", "address": "8310 Mira Mesa Blvd, San Diego, CA"},
  {"retailer": "Vons", "machineId": "Q00506", "address": "515 Washington St, San Diego, CA"},
  {"retailer": "Albertsons", "machineId": "Q00572", "address": "12475 Rancho Bernardo Rd, San Diego, CA"},
  {"retailer": "Vons", "machineId": "Q00576", "address": "7544 Girard Ave, San Diego, CA"},
  {"retailer": "Albertsons", "machineId": "Q00581", "address": "8650 Lake Murray Blvd, San Diego, CA"},
  {"retailer": "Vons", "machineId": "Q00592", "address": "4145 30th St, San Diego, CA"},
  {"retailer": "Vons", "machineId": "Q00615", "address": "4725 Clairemont Dr, San Diego, CA"},
  {"retailer": "Vons", "machineId": "Q00888", "address": "3550 Murphy Canyon Rd, San Diego, CA"},
  {"retailer": "Vons", "machineId": "Q00889", "address": "10675 Scripps Poway Pkwy, San Diego, CA"},
  {"retailer": "Vons", "machineId": "Q01266", "address": "7895 Highlands Village Pl, San Diego, CA"},
  {"retailer": "Albertsons", "machineId": "Q00496", "address": "220 E Bonita Ave, San Dimas, CA"},
  {"retailer": "Safeway", "machineId": "Q00920", "address": "735 7th Ave, San Francisco, CA"},
  {"retailer": "Safeway", "machineId": "Q01335", "address": "850 La Playa St, San Francisco, CA"},
  {"retailer": "Safeway", "machineId": "Q01345", "address": "5290 Diamond Heights Blvd, San Francisco, CA"},
  {"retailer": "Lucky", "machineId": "Q00921", "address": "3457 McKee Rd, San Jose, CA"},
  {"retailer": "Safeway", "machineId": "Q00925", "address": "5760 Cottle Rd, San Jose, CA"},
  {"retailer": "Safeway", "machineId": "Q00934", "address": "1663 Branham Ln, San Jose, CA"},
  {"retailer": "Safeway", "machineId": "Q00937", "address": "4950 Almaden Expy, San Jose, CA"},
  {"retailer": "Safeway", "machineId": "Q00986", "address": "179 Branham Ln, San Jose, CA"},
  {"retailer": "Safeway", "machineId": "Q00991", "address": "1530 Hamilton Ave, San Jose, CA"},
  {"retailer": "Safeway", "machineId": "Q01526", "address": "5146 Stevens Creek Blvd, San Jose, CA"},
  {"retailer": "Safeway", "machineId": "Q00623", "address": "1799 Marlow Rd, Santa Rosa, CA"},
  {"retailer": "Safeway", "machineId": "Q00632", "address": "100 Calistoga Rd, Santa Rosa, CA"},
  {"retailer": "Safeway", "machineId": "Q00672", "address": "2300 Mendocino Ave, Santa Rosa, CA"},
  {"retailer": "Safeway", "machineId": "Q00976", "address": "2751 4th St, Santa Rosa, CA"},
  {"retailer": "FoodMaxx", "machineId": "Q01256", "address": "2055 Sebastopol Rd, Santa Rosa, CA"},
  {"retailer": "Safeway", "machineId": "Q01339", "address": "1211 W College Ave, Santa Rosa, CA"},
  {"retailer": "Safeway", "machineId": "Q01484", "address": "2785 Yulupa Ave, Santa Rosa, CA"},
  {"retailer": "Vons", "machineId": "Q01655", "address": "9643 Mission Gorge Rd, Santee, CA"},
  {"retailer": "Safeway", "machineId": "Q01521", "address": "12876 Saratoga Sunnyvale Rd, Saratoga, CA"},
  {"retailer": "Safeway", "machineId": "Q01331", "address": "253 Mt Hermon Rd, Scotts Valley, CA"},
  {"retailer": "WinCo Foods", "machineId": "Q01325", "address": "2850 Pavilion Pkwy, Tracy, CA"},
  {"retailer": "Albertsons", "machineId": "Q00348", "address": "13270 Newport Ave, Tustin, CA"},
  {"retailer": "Safeway", "machineId": "Q00979", "address": "1790 Decoto Rd, Union City, CA"},
  {"retailer": "Albertsons", "machineId": "Q00661", "address": "1910 N Campus Ave, Upland, CA"},
  {"retailer": "Vons", "machineId": "Q00731", "address": "101 W Foothill Blvd, Upland, CA"},
  {"retailer": "Safeway", "machineId": "Q01346", "address": "2090 Harbison Dr, Vacaville, CA"},
  {"retailer": "Safeway", "machineId": "Q01523", "address": "122 Robles Way, Vallejo, CA"},
  {"retailer": "Vons", "machineId": "Q01123", "address": "115 W Main St, Ventura, CA"},
  {"retailer": "Albertsons", "machineId": "Q00488", "address": "1301 E Vista Way, Vista, CA"},
  {"retailer": "Albertsons", "machineId": "Q00516", "address": "1601 S Melrose Dr, Vista, CA"},
]

export default vendingData;